Add update operation to volume resource
dell/terraform-provider-powerstore pull request #12
Opened 2022-11-07 15:10 UTC by Sakshi-dell

# Description
Added Update operation for volume resource.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2022-11-09 16:45 UTC, mkmayank-dell commented on go.mod
> +	github.com/dell/gopowerstore v1.9.1-0.20221107105409-fc93e33a4f9b
this commit id not a good idea , as we already discussed

2022-11-09 16:56 UTC, mkmayank-dell approved these changes

2022-11-09 17:05 UTC, shenda1 commented on powerstore/resource_volume.go
> +			"capacity_unit": {
Can we have default value for capacity_unit?

2022-11-14 14:12 UTC, mkmayank-dell requested changes

2022-11-14 14:12 UTC, mkmayank-dell commented on powerstore/volume_helper.go
> +	volState.CapacityUnit.Value = unit
For line 30, `if operation == "Create" || operation == "Update" `
Better way would be plan Modifiers,  whether independent for every attribute or ResourceWithPlanModifier for everyone at single place

2022-11-15 05:43 UTC, mkmayank-dell approved these changes

2022-11-15 14:44 UTC, shenda1 approved these changes

2022-11-15 14:50 UTC, merged